openapi: 3.1.0
info:
  title: Bank Argent API - Transactions Module
  description: API endpoints for managing user transactions
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
  contact:
    name: API Support
    email: support@bankargent.com
servers:
  - url: http://localhost:3001/api/v1
security:
  - bearerAuth: []
tags:
  - name: Transactions
    description: Everything related to banking transactions
paths:
  /account/{accountID}:
    get:
      tags:
        - Transactions
      summary: Retrieve all transactions for the current month grouped by account
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
          required: true
          description: Attach Bearer JWT token
        - in: path
          name: accountID
          schema:
            type: string
          required: true
          description: Account ID
      responses:
        '200':
          description: List of transactions retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfTransactions'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/ServerError'
  /transaction/{transactionId}:
    get:
      tags:
        - Transactions
      summary: Retrieve transaction details
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
          required: true
          description: Attach Bearer JWT token
        - in: path
          name: transactionId
          schema:
            type: string
          required: true
          description: Transaction ID
      responses:
        '200':
          description: Transaction details retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
        '404':
          description: Transaction not found
        '500':
          $ref: '#/components/responses/ServerError'
    patch:
      tags:
        - Transactions
      summary: Modify transaction details
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
          required: true
          description: Attach Bearer JWT token
        - in: path
          name: transactionId
          schema:
            type: string
          required: true
          description: Transaction ID
      requestBody:
        description: Update transaction attributes
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionUpdate'
      responses:
        '200':
          description: Transaction updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
        '400':
          $ref: '#/components/responses/InvalidFields'
        '404':
          description: Transaction not found
        '500':
          $ref: '#/components/responses/ServerError'
    delete:
      tags:
        - Transactions
      summary: Delete a transaction
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
          required: true
          description: Attach Bearer JWT token
        - in: path
          name: transactionId
          schema:
            type: string
          required: true
          description: Transaction ID
      responses:
        '200':
          description: Transaction deleted successfully
        '404':
          description: Transaction not found
        '500':
          $ref: '#/components/responses/ServerError'
  /transactions/new:
    post:
      tags:
        - Transactions
      summary: Create a new transaction
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
          required: true
          description: Attach Bearer JWT token
      requestBody:
        description: Transaction details
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionCreate'
      responses:
        '201':
          description: Transaction created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
        '400':
          $ref: '#/components/responses/InvalidFields'
        '500':
          $ref: '#/components/responses/ServerError'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Transaction:
      type: object
      properties:
        id:
          type: string
        date:
          type: string
          format: date-time
        amount:
          type: number
        type:
          type: string
          enum: [credit, debit]
        category:
          type: string
        description:
          type: string
    ArrayOfTransactions:
      type: array
      items:
        $ref: '#/components/schemas/Transaction'
    TransactionCreate:
      type: object
      properties:
        date:
          type: string
          format: date-time
        amount:
          type: number
        type:
          type: string
          enum: [credit, debit]
        category:
          type: string
        description:
          type: string
    TransactionUpdate:
      type: object
      properties:
        category:
          type: string
        description:
          type: string
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
    ServerError:
      description: Internal Server Error
    InvalidFields:
      description: Invalid input fields